
version: '3'
services:
  db:
    image: mysql:8.0
    # 環境変数
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USERNAME: root
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
    # port解放
    expose:
      - 3307
    ports:
      # - '3306:3306'
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    # .のDockerfileをbuildする
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      # .をmyappにmount
      - .:/myapp
    ports:
      # host to container
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local

